---
title: "EDS"
output: html_document
date: "2022-11-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(purrr)#to join all files
```


#joining four months in one sheet
```{r}
#bind all the files in this path together
file.list <- list.files(pattern='*.csv')

# need an id-column with the file-names
file.list <- setNames(file.list, file.list)

#want only sheet 4, skip 1 row and name id column month
bike <-map_df(file.list, function(x) read.csv(x))

str(bike)
```

#Preparing columns for modeling
```{r}
#bike <- data.frame(read.csv("bo.csv"))
bike$rideable_type <- factor(bike$rideable_type)
bike$member_casual <- factor(bike$member_casual)
# split started_at/ ended_at to date column and time column
# change start_date/end_date to date type
bike$start_time <- format(as.POSIXct(bike$started_at), format = "%H:%M") 
bike$end_time <- format(as.POSIXct(bike$ended_at), format = "%H:%M") 
bike$start_date <- as.Date(bike$started_at)
bike$end_date <- as.Date(bike$ended_at)
bike$Startedat = as.POSIXct(bike$started_at, format = "%Y-%m-%d %H:%M:%S")
bike$enddat = as.POSIXct(bike$ended_at, format = "%Y-%m-%d %H:%M:%S")
bike$Total_Time <- round(as.numeric(difftime(bike$enddat, bike$Startedat, units = "mins")),2)
#take the day to another column and delete the year and month
```
## need to check for codes for times and days being rounded not bigger or lower

```{r}


```


##Drop non-needed columns
```{r}
drop <- c('Startedat','enddat','started_at','ended_at', 'start_station_name', 'end_station_name', 'start_lat', 'end_lat', 'start_lng','end_lng')
df <- bike[,!(names(bike) %in% drop)]

```


#find the most influnsing factors
```{r}
agesurvive = xtabs(~ member_casual + rideable_type, data = df)
chisq.test(agesurvive)
```

they are dependent factors

```{r}
agesurvive2 = xtabs(~ member_casual + Total_Time, data = df)
chisq.test(agesurvive2)
```

This is better

```{r}
agesurvive3 = xtabs(~ member_casual + start_station_id , data = df)
chisq.test(agesurvive3)
```

Interestingly very low p-value

```{r}
agesurvive4 = xtabs(~ member_casual + end_station_id , data = df)
chisq.test(agesurvive4)
```

Again low p-value

```{r}
admitLogit <- glm(member_casual ~ end_station_id+start_station_id+Total_Time+rideable_type, data = df, family = "binomial")
summary(admitLogit)
```